# Build stage
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app

COPY ../variables.test.env ./
COPY ../gradlew .
COPY ../gradle/ gradle/

RUN chmod +x /app/gradlew

COPY ../build.gradle.kts ../settings.gradle.kts ./

COPY ../src/ src/

RUN /app/gradlew --no-daemon bootJar \
    -x test \
    -x integrationTest \
    -x archTest \
    -x detekt \
    -x ktlintCheck \
    -Dorg.gradle.dependency.verification=off \
    --stacktrace

# Runtime stage
FROM eclipse-temurin:21-jre-alpine
RUN apk add --no-cache curl
WORKDIR /app

RUN addgroup -S app && adduser -S app -G app

COPY --from=build /app/build/libs/*.jar app.jar

USER app

ENTRYPOINT ["java","-jar","/app/app.jar"]