### Webhook: create order
POST http://localhost:8000/api/v1/webhooks
Content-Type: application/json
Authorization: marketplace-service-secret

{
  "store_ids": [
    "store-1"
  ],
  "callback_url": "http://receiver-service:8001/api/v1/events",
  "token": "receiver-service-secret"
}

### Orders: create order
POST http://localhost:8000/api/v1/orders
Content-Type: application/json
Authorization: marketplace-service-secret

{
  "store_id": "store-1",
  "items": [
    {
      "product_name": "Placa de video RTX 5090",
      "quantity": 1,
      "unit_price": 8980,
      "discount": 100,
      "tax": 10
    }
  ]
}

### Orders: atualizar status da order
PATCH http://localhost:8000/api/v1/orders/cf062c2f-0a31-472c-a34f-356f9461014f/status
Content-Type: application/json
Authorization: marketplace-service-secret

{
  "status": "PAID"
}